// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type Transaction struct {
	ID              interface{}
	CreatedAt       time.Time
	UpdatedAt       time.Time
	TransactionType interface{}
	TransactedOn    time.Time
	AmountCents     int64
}
